---
title: "Microbial assoication network"
author: "Mansi"
date: "6/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load the packages
library(devtools)
library(SpiecEasi)
library(phyloseq)
library(seqtime)

```


```{r}
#load the dataset

input.path = "/Users/mansichandra/Desktop/PSU Research/SPIEC-EASI"
output.path = "/Users/mansichandra/Desktop/PSU Research/SPIEC-EASI"
biom.path = file.path(input.path, "TwinsUK_Batch3_OTU_table_w_tax_rarefied_10000_networks_50_percent_presence_pruned_json.biom")

```


```{r}
#Extract OTU table and taxonomy table

phyloseqobj=import_biom(biom.path)
otus=otu_table(phyloseqobj)
taxa=tax_table(phyloseqobj)
```


```{r}
#Filter the OTU table

filterobj = filterTaxonMatrix(otus, minocc = 20, keepSum = TRUE, return.filtered.indices = TRUE)
otus.f=filterobj$mat
taxa.f=taxa[setdiff(1:nrow(taxa),filterobj$filtered.indices),]
dummyTaxonomy=c("k__dummy","p__","c__","o__","f__","g__","s__")
taxa.f=rbind(taxa.f,dummyTaxonomy)
rownames(taxa.f)[nrow(taxa.f)]="0"
rownames(otus.f)[nrow(otus.f)]="0"

```


```{r}
#assemble a new phyloseq object with filtered OTU and taxonomy table

updatedotus=otu_table(otus, taxa_are_rows = TRUE)
updatedtaxa=tax_table(taxa)
phyloseqobj.f=phyloseq(updatedotus, updatedtaxa)
```


```{r}
#Run SPIEC-EASI (make model)

spiec.out=spiec.easi(phyloseqobj.f, method="mb",icov.select.params=list(rep.num=20))

```


```{r}
#Convert the SPIEC-EASI output to a network and plot the network

spiec.graph=adj2igraph(getRefit(spiec.out), vertex.attr=list(name=taxa_names(phyloseqobj.f)))

plot_network(spiec.graph, phyloseqobj.f, type='taxa', color="Rank3", label=NULL)

```


```{r}
#Generate regression matrix and calculate positive and negative edges 
betaMat=as.matrix(symBeta(getOptBeta(spiec.out)))
positive=length(betaMat[betaMat>0])/2 
negative=length(betaMat[betaMat<0])/2 
total=length(betaMat[betaMat!=0])/2 
```


```{r}

otu.ids=colnames(spiec.out$data)
edges=E(spiec.graph)
edge.colors=c()
for(e.index in 1:length(edges)){
	adj.nodes=ends(spiec.graph,edges[e.index])
	xindex=which(otu.ids==adj.nodes[1])
	yindex=which(otu.ids==adj.nodes[2])
	beta=betaMat[xindex,yindex]
	if(beta>0){
		edge.colors=append(edge.colors,"forestgreen")
	}else if(beta<0){
		edge.colors=append(edge.colors,"red")
	}
}
E(spiec.graph)$color=edge.colors

```


```{r}
clusters=cluster_fast_greedy(spiec.graph)
clusterOneIndices=which(clusters$membership==1)
clusterOneOtus=clusters$names[clusterOneIndices]
clusterTwoIndices=which(clusters$membership==2)
clusterTwoOtus=clusters$names[clusterTwoIndices]
```


```{r}
sort(table(getTaxonomy(clusterOneOtus,taxa.f,useRownames = TRUE)),decreasing = TRUE)
sort(table(getTaxonomy(clusterTwoOtus,taxa.f,useRownames = TRUE)),decreasing = TRUE)

```


